config/routes.rb
Rails.application.routes.draw do
  resources :forums

  get 'forum(/:page(/:tags))', to: 'forum#index', as: 'forum_index'
  post 'forum/search_by_tags', to: 'forum#search_by_tags', as: 'search_by_tags'
  post 'forum/search_by_page', to: 'forum#search_by_page', as: 'search_by_page'
  post 'forum/create_post', to: 'forum#create_post', as: 'create_post'
  post 'forum/toggle_post_like', to: 'forum#toggle_post_like', as: 'toggle_post_like'
  post 'forum/create_comment', to: 'forum#create_comment', as: 'create_comment'
  post 'forum/toggle_comment_like', to: 'forum#toggle_comment_like', as: 'toggle_comment_like'

  get 'login', to: 'login#index', as: 'login_index'
  post 'login', to: 'login#login'

  get 'register', to: 'register#index', as: 'register_index'
  post 'register', to: 'register#register'

  get 'user/:login', to: 'user#profile', as: 'user_profile'
  post 'user/logout', to: 'user#logout', as: 'user_logout'
  post 'user/changeAvatar', to: 'user#change_avatar'
  post 'user/changeDescription', to: 'user#change_description'
  post 'user/toggleFriend', to: 'user#toggle_friend', as: 'toggle_friend'

  get "up" => "rails/health#show", as: :rails_health_check

   root "forum#index"
end

Rails.application.routes.default_url_options[:host] = 'localhost:3000'

app/controllers/forum_controller.rb
$MAX_POSTS_PER_PAGE = 5

class ForumController < ApplicationController
  def get_posts_dto(page_id, tags)
    page_id = page_id >= 0 ? page_id : 0
    posts = Post.order(id: :desc)
  
    unless tags.blank?
      tags_array = tags.split(' ')
        .select { |tag| tag.length >= 3 }
        .take(10)
        .map { |tag| tag.length > 25 ? tag[0, 25] : tag }
        .uniq
  
      posts = posts.joins(:tags).where(tags: { name: tags_array })
    end
  
    posts = posts.offset(page_id * $MAX_POSTS_PER_PAGE).limit($MAX_POSTS_PER_PAGE)
    @posts = posts.map(&:to_dto)
  end
  
  
  def index
    @page = params[:page].to_i
    @tags = params[:tags]

    session[:page] = @page
    session[:tags] = @tags

    page_id = @page >= 0 ? @page : 0
    @posts_dto = get_posts_dto(page_id, @tags)
  end

  def show
  end

  def search_by_tags
    tags = params[:tags]
    choice = params[:choice].to_i
  
    if (choice == 0 && !tags.blank?)
      redirect_to action: "index", page: 0, tags: tags
    else
      redirect_to action: "index", page: 0, tags: ""
    end
  end

  def search_by_page
    page = params[:page].to_i
    tags = params[:tags].presence || ""
  
    redirect_to action: "index", page: (page.present? && page > 0 ? page : 0), tags: tags
  end
  

  def create_post
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
  
    login = session[:user]['login']
    user = User.find_by(login: login)
  
    if user.nil?
      redirect_to login_index_path
      return
    end
  
    title = params[:title]
    content = params[:content]
    tags = params[:tags]
  
    if title.blank?
      @error_message = "Nie podano tytułu."
      redirect_to action: "index", page: session[:page], tags: session[:tags]
      return
    end
  
    if content.blank?
      @error_message = "Nie podano treści."
      redirect_to action: "index", page: session[:page], tags: session[:tags]
      return
    end
  
    post = Post.new
    post.title = title.length > 255 ? title[0, 255] : title
    post.content = content
    post.created_at = Time.now
    post.user_id = user.id
  
    unless tags.blank?
      tags_array = tags.split(' ').select { |tag| tag.length >= 3 }
        .take(10)
        .map { |tag| tag.length > 25 ? tag[0, 25] : tag }
        .uniq
  
      tags_array.each do |tag_name|
        new_tag = Tag.new(name: tag_name)
        post.tags << new_tag
      end
    end
  
    if post.save
      redirect_to action: "index", page: session[:page], tags: session[:tags]
    else
      @error_message = "Wystąpił błąd podczas zapisywania posta."
      redirect_to action: "index", page: session[:page], tags: session[:tags]
    end
  end  
  
  def toggle_post_like
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
    
    login = session[:user]['login']
    user = User.find_by(login: login)
  
    if user.nil?
      redirect_to login_index_path
      return
    end
    
    post_id = params[:post_id]
    post = Post.find_by(id: post_id)
  
    if post.nil?
      redirect_to action: "index", page: session[:page], tags: session[:tags]
      return
    end
  
    if post.post_likes.exists?(user_id: user.id)
      post.post_likes.find_by(user_id: user.id).destroy
    else
      post.post_likes.create(user_id: user.id)
    end
    
    respond_to do |format|
      format.html { redirect_to action: "index", page: session[:page], tags: session[:tags] }
      format.json { render json: { post_id: post.id, likes: post.post_likes.count } }
      format.turbo_stream { render turbo_stream: turbo_stream.replace("post_like_count_#{post_id}", partial: "post_like_count", locals: { likes: post.post_likes.count }) }
    end
  end  

  def create_comment
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
  
    login = session[:user]['login']
    user = User.find_by(login: login)
  
    if user.nil?
      redirect_to login_index_path
      return
    end
  
    post_id = params[:post_id]
    content = params[:content]
  
    if content.blank?
      @error_message = "Nie podano treści."
      redirect_to action: "index", page: session[:page], tags: session[:tags]
      return
    end

    comment = Comment.new
    comment.content = content
    comment.created_at = Time.now
    comment.user_id = user.id
    comment.post_id = post_id
  
    if comment.save
      redirect_to action: "index", page: session[:page], tags: session[:tags]
    else
      @error_message = "Wystąpił błąd podczas zapisywania komentarza."
      redirect_to action: "index", page: session[:page], tags: session[:tags]
    end
  end

  def toggle_comment_like
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
    
    login = session[:user]['login']
    user = User.find_by(login: login)
  
    if user.nil?
      redirect_to login_index_path
      return
    end
    
    comment_id = params[:comment_id]
    comment = Comment.find_by(id: comment_id)
  
    if comment.nil?
      redirect_to action: "index", page: session[:page], tags: session[:tags]
      return
    end
  
    if comment.comment_likes.exists?(user_id: user.id)
      comment.comment_likes.find_by(user_id: user.id).destroy
    else
      comment.comment_likes.create(user_id: user.id)
    end
    
    redirect_to action: "index", page: session[:page], tags: session[:tags]
  end
end
  

app/views/forum/_add_comment.html.erb
<%= form_with(url: create_comment_path, method: :post, class: "my-3") do |form| %>
  <div class="field">
    <%= form.hidden_field :post_id, value: post_id %>
    <div class="control">
      <%= form.text_area :content, id: "content", class: "textarea", required: true %>
    </div>
  </div>
  <div class="field">
    <div class="control has-text-right">
      <%= form.submit "Dodaj komentarz", class: "button is-primary" %>
    </div>
  </div>
<% end %>

app/views/forum/_add_post.html.erb
<%= turbo_frame_tag 'New_post' do %>
  <%= form_tag create_post_path, method: :post, class: "has-background-black-ter box is-rounded is-standard-width" do %>
    <div class="field">
      <div class="control">
        <%= text_field_tag :title, nil, placeholder: "Wprowadź tytuł", class: "input is-medium" %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= text_area_tag :content, nil, placeholder: "Wprowadź treść", class: "textarea is-medium" %>
      </div>
    </div>

    <div class="control">
      <%= text_field_tag :tags, nil, id: "tags", placeholder: "Wprowadź tagi (opcjonalne, odziel spacją)", class: "input is-medium" %>
    </div>

    <% unless @error_message.nil? %>
      <div class="has-text-centered my-4 has-text-danger"><%= @error_message %></div>
    <% end %>

    <div class="field mt-3">
      <div class="control has-text-right">
        <%= submit_tag "Dodaj post", class: "button is-primary is-fullwidth is-medium" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/forum/_author_info.html.erb
<div class="mb-3 columns m-0 p-0" style="width:100%; height: 50px;">
    <div class="column is-narrow p-0 m-0 is-flex is-align-items-center">
        <% if avatar_url.nil? %>
            <span class="icon mx-3">
                <i class="fas fa-user" style="font-size: 50px;"></i>
            </span>
        <% else %>
            <img src="<%= avatar_url %>"
                alt="Avatar"
                style= "width: 50px; height: 50px; border-radius: 50%; object-fit: cover; object-position: center;" />
        <% end %>
    </div>

    <div class="column columns m-0 p-0 ml-3 is-flex is-flex-direction-column">
        <div class="column m-0 p-0 is-flex">
            <span>Dodano przez:</span>
            <%= link_to user_profile_path(login) do %>
                <span class="ml-1"><%= login %></span>
            <% end %>
        </div>
        <span class="column m-0 p-0"><%= created_at.strftime("%d.%m.%Y - %H:%M") %></span>
    </div>
</div>

app/views/forum/_comment.html.erb
<div class="has-background-grey-darker py-3 box is-rounded has-text-white">
    <%= render partial: "forum/author_info", locals: { login: comment_dto.user_login, created_at: comment_dto.created_at, avatar_url: comment_dto.avatar_url } %>
    <p class="is-size-5 pr-5" style="max-height: 480px; overflow-y: auto;">
        <%= comment_dto.content %>
    </p>

    <div class="is-align-items-center is-justify-content-flex-end is-flex m-0 p-0 mt-3">
        <span class="icon-text">
            <%= form_with(url: toggle_comment_like_path, method: :post) do |form| %>
                <%= form.hidden_field :comment_id, value: comment_dto.id %>
                <% if @is_logged %>
                    <%= form.button class: "icon fa-regular has-text-info-40 is-size-4", type: "submit" do %>
                        <i class="fas fa-thumbs-up is-5" style="cursor: pointer;"></i>
                    <% end %>
                <% else %>
                    <%= form.button class: "icon fa-regular has-text-info-40 is-size-4", type: "submit", disabled: true do %>
                        <i class="fas fa-thumbs-up is-5"></i>
                    <% end %>
                <% end %>
            <% end %>
            <span class="ml-1"><%=comment_dto.likes%></span>
        </span>
    </div>
</div>

app/views/forum/_page_navigation.html.erb
<%
  @is_previous_disabled = @page == 0
  @is_next_disabled = @posts_dto.count < $MAX_POSTS_PER_PAGE
%>

<%= form_with(url: search_by_page_path, method: :post, class: "m-0 p-0 has-text-centered is-flex is-align-items-center is-justify-content-center") do |form| %>
  <%= form.hidden_field :tags, value: @tags %>
  <%= form.button class: "button is-primary is-medium mr-5", type: "submit", name: "page", value: @page - 1, disabled: @is_previous_disabled do %>
    Poprzednia strona
  <% end %>

  <span class="is-size-3 has-text-white m-0 p-0"><%= @page %></span>

  <%= form.button class: "button is-primary is-medium ml-5", type: "submit", name: "page", value: @page + 1, disabled: @is_next_disabled do %>
    Następna strona
  <% end %>
<% end %>

app/views/forum/_post.html.erb
<div class="has-background-black-ter box is-rounded my-3">
    <%= render partial: "forum/author_info", locals: { login: post_dto.user_login, created_at: post_dto.created_at, avatar_url: post_dto.avatar_url } %>

    <div class="pr-5" style="max-height: 480px; overflow-y: auto;">
		<p class="is-size-4 has-text-white"><%= post_dto.title %></p>
		<p class="is-size-5"><%= post_dto.content %></p>
	</div>

     <% if @is_logged %>
        <%= render partial: "forum/add_comment", locals: { post_id: post_dto.id } %>
     <% end %>

    <% if post_dto.comments.count > 0 %>
        <div class="my-3 pr-3" style="max-height: 480px; overflow-y: auto">
            <% post_dto.comments.each do |comment_dto| %>
                <%= render partial: "comment", locals: { comment_dto: comment_dto, is_logged: @is_logged } %>
            <% end %>
        </div>
    <% end %>

    <div class="columns mt-1">
        <div class="column mr-3 is-flex">
            <% post_dto.tags.each do |tag| %>
                <%= render partial: "tag", locals: { tag: tag } %>
            <% end %>
        </div>

        <div class="column is-narrow is-flex is-align-items-end ml-3">
            <%= render partial: "toggle_post_like",
            locals: { post_id: post_dto.id, likes: post_dto.likes } %>
            

            <span class="icon-text ml-5">
				<span class="icon fa-regular has-text-info-40 is-size-4"><i class="fas fa-comment" style="cursor: pointer;"></i></span>
				<span class="ml-1"><%= post_dto.comments.count %></span>
			</span>
        </div>
    </div>
</div>

app/views/forum/_search_post.html.erb
<%= form_with(url: search_by_tags_path, method: :post, class: "is-flex") do |form| %>
  <div class="field">
    <div class="control">
      <%= text_field_tag :tags, nil, placeholder: "Wprowadź tagi (po spacji)", class: "input is-medium m-0", value: @tags %>
    </div>
  </div>

  <div class="field ml-3">
    <div class="control">
      <%= form.button class: "button is-primary is-fullwidth is-medium", type: "submit", name: "choice", value: "0" do %>
        Wyszukaj
      <% end %>
    </div>
  </div>

  <div class="field ml-3">
    <div class="control">
      <%= form.button class: "button is-primary is-fullwidth is-medium", type: "submit", name: "choice", value: "1" do %>
        Wyczyść
      <% end %>
    </div>
  </div>
<% end %>

app/views/forum/_tag.html.erb
<%= form_with(url: search_by_tags_path, method: :post, class: "is-flex") do |form| %>
    <%= form.hidden_field :tags, value: tag.name %>
    <%= form.button class: "has-text-link mr-1", type: "submit", name: "choice", value: "0" do %>
        #<%= tag.name %>
    <% end %>    
<% end %>

app/views/forum/_toggle_post_like.html.erb
<%= turbo_frame_tag 'Toggle_post_like' do %>
    <% @is_logged = session[:user].present? %>
    <%= form_with(url: toggle_post_like_path, method: :post, class: "icon-text") do |form| %>
        <%= form.hidden_field :post_id, value: post_id %>
        <% if @is_logged %>
            <%= form.button class: "icon fa-regular has-text-info-40 is-size-4", type: "submit" do %>
                <i class="fas fa-thumbs-up is-5" style="cursor: pointer;"></i>
            <% end %>
        <% else %>
            <%= form.button class: "icon fa-regular has-text-info-40 is-size-4", type: "submit", disabled: true do %>
                <i class="fas fa-thumbs-up is-5"></i>
            <% end %>
        <% end %>
    <% end %>
    <span class="ml-2"><%= likes %></span>
<% end %>

app/views/forum/index.html.erb
<% @is_logged = session[:user].present? %>

<div class="columns is-flex is-flex-direction-column is-align-items-center p-3" style="width: 100%; height: 100%">
    <div class="column is-narrow p-0 m-0 is-flex is-justify-content-flex-end" style="width: 100%">
        <%= render partial: "forum/search_post" %>
    </div>

     <% if @is_logged && @page == 0 %>
        <%= turbo_frame_tag 'New_post' do %>
            <div class="column is-narrow p-0 m-0">
                <%= render "add_post" %>
            </div>
        <% end %>  
     <% end %>

    <%= turbo_frame_tag 'Posts' do %>
        <div class="column p-0 m-0 is-standard-width">
            <% @posts_dto.each do |post_dto| %>
                <%= render "post", post_dto: post_dto, is_logged: @is_logged %>
            <% end %>
        </div>
    <% end %>

     <div class="column is-narrow">
        <%= render partial: "forum/page_navigation" %>
     </div>
</div>

app/views/forum/toggle_post_like.turbo_stream.erb
<%= turbo_stream.replace "post_like_count_#{post_id}", partial: "post_like_count", locals: { likes: likes } %>