config/routes.rb
Rails.application.routes.draw do
  resources :forums

  get 'forum(/:page(/:tags))', to: 'forum#index', as: 'forum_index'
  post 'forum/search_by_tags', to: 'forum#search_by_tags', as: 'search_by_tags'
  post 'forum/search_by_page', to: 'forum#search_by_page', as: 'search_by_page'
  post 'forum/create_post', to: 'forum#create_post', as: 'create_post'
  post 'forum/toggle_post_like', to: 'forum#toggle_post_like', as: 'toggle_post_like'
  post 'forum/create_comment', to: 'forum#create_comment', as: 'create_comment'
  post 'forum/toggle_comment_like', to: 'forum#toggle_comment_like', as: 'toggle_comment_like'

  get 'login', to: 'login#index', as: 'login_index'
  post 'login', to: 'login#login'

  get 'register', to: 'register#index', as: 'register_index'
  post 'register', to: 'register#register'

  get 'user/:login', to: 'user#profile', as: 'user_profile'
  post 'user/logout', to: 'user#logout', as: 'user_logout'
  post 'user/changeAvatar', to: 'user#change_avatar'
  post 'user/changeDescription', to: 'user#change_description'
  post 'user/toggleFriend', to: 'user#toggle_friend', as: 'toggle_friend'

  get "up" => "rails/health#show", as: :rails_health_check

   root "forum#index"
end

Rails.application.routes.default_url_options[:host] = 'localhost:3000'

app/models/user.rb
include Rails.application.routes.url_helpers
class User < ApplicationRecord
    has_many :posts
    has_many :comments
    has_many :post_likes
    has_many :comment_likes
  
    validates :login, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 50 }, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, presence: true, length: { maximum: 100 }
    has_one_attached :avatar
    validates :description, length: { maximum: 3000 }, allow_blank: true
    
    before_save :set_created_at
    
    has_many :friendships
    has_many :friends, through: :friendships

    def get_avatar_url
      return self.avatar.attached? ? rails_blob_url(self.avatar) : nil
    end

    private
    def set_created_at
      self.created_at ||= Time.now
    end
  end
  

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile
    @login = params[:login]
    user = User.find_by(login: @login)

    if user.present?
      @profile = UserProfile.new(
        login: user.login,
        created_at: user.created_at,
        avatar_url: user.avatar.attached? ? rails_blob_url(user.avatar) : nil,
        description: user.description,
        posts_count: user.posts.count,
        comments_count: user.comments.count,
        likes_count: user.post_likes.count + user.comment_likes.count,
        is_my_friend: is_my_friend(user)
      )

      if session[:user].present? && session[:user]['login'] == user.login
        @profile.friends = user.friends
      end
    else
      @profile = nil
    end
  end

  def change_avatar
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
    
    login = session[:user]['login']
    user = User.find_by(login: login)
  
    return redirect_to login_index_path if user.nil?
  
    avatar = params[:avatar]
  
    if avatar.present?
      user.avatar.attach(avatar)
    end
  
    redirect_to action: "profile", login: user.login
  end   

  def change_description
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
    
    login = session[:user]['login']
    user = User.find_by(login: login)
    
    return redirect_to login_index_path if user.nil?
    
    new_description = params[:description]
    user.update(description: new_description)
    
    redirect_to action: "profile", login: user.login
  end
  
  def toggle_friend
    p 'test'
    unless session[:user].present?
      redirect_to login_index_path
      return
    end
    
    friend_login = params[:login]
    friend = User.find_by(login: friend_login)

    return redirect_to login_index_path if friend.nil?

    current_user = User.find_by(login: session[:user]['login'])

    if current_user.friends.include?(friend)
      current_user.friends.delete(friend)
    else
      current_user.friends << friend
    end

    redirect_to action: "profile", login: friend_login
  end

  def logout
    session.delete(:user) if session[:user].present?
    redirect_to forum_index_path
  end

  private

  def is_my_friend(user)
    return false unless session[:user].present?
    return false if session[:user]['login'] == user.login

    current_user = User.find_by(login: session[:user]['login'])
    return current_user.friends.include?(user)
  end
end

app/views/user/_profile_avatar.html.erb
<div style="width: 100%; height: 100%; cursor: <%= is_my_account ? 'pointer' : 'auto' %>; overflow: hidden;" id="avatarContainer">
  <% if avatar_url.present? %>
    <img src="<%= avatar_url %>"
      alt="Avatar"
      style="width: 200px; height: 200px; border-radius: 50%; object-fit: cover; object-position: center;" />
  <% else %>
    <span class="icon" style="width: 100%; height: 100%;">
      <i class="fas fa-user p-3" style="font-size: 200px;"></i>
    </span>
  <% end %>
</div>

<form id="changeAvatarForm" method="post" enctype="multipart/form-data" style="display: none;">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="file" id="avatarInput" name="avatar" accept="image/*">
</form>


<script>
    document.addEventListener("DOMContentLoaded", function() {
        let avatarInput = document.getElementById("avatarInput");
        if (avatarInput !== null)
        {
            document.getElementById("avatarContainer").addEventListener("click", function () {
                avatarInput.click();
            });

            avatarInput.addEventListener("change", function (event) {
                var file = event.target.files[0];
                var formData = new FormData();
                formData.append("avatar", file);
                var csrfToken = document.querySelector('meta[name="csrf-token"]').content;

                fetch("/user/changeAvatar", {
                method: "POST",
                headers: {
                    "X-CSRF-Token": csrfToken
                },
                body: formData,
                })
                .then((response) => {
                    if (response.ok) {
                      location.reload();
                    } else {
                      alert("Wystąpił błąd podczas zmiany awatara.");
                    }
                })  
                .catch((error) => {
                    alert("Wystąpił błąd podczas wysyłania danych.");
                });
            });
        }
    });
</script>

app/views/user/_profile_description.html.erb
<div id="descriptionContainer" class="column columns p-0 m-0"
	 style="width: 100%; cursor: <%= is_my_account ? "pointer" : "auto" %>;">

    <script>
        const container = document.getElementById("descriptionContainer");
        let description = `<%= description %>`.trim();
        let isMyAccount = `<%= is_my_account %>`;

        function initText() {
            const text = (description !== "") ? description : (isMyAccount === true ? "Kliknij, by edytować opis." : "Brak opisu.");
            container.innerHTML =
                container.innerHTML = `
            <div class="px-5 py-0 my-3 is-flex column" style="width: 100%; height: 100%;">
                <span id="textContainer"
                    style="overflow-y: auto; max-height: 125px;">${text}
                </span>
            </div>`

            if (isMyAccount) {
                const textContainer = document.getElementById("textContainer")
                textContainer.addEventListener('click', () => {
                    initInput();
                });
            }
        }

        function initInput() {
            container.innerHTML = `
            <div class="px-5 py-0 my-3 is-flex columns column" style="width: 100%;">
                <textarea id="descriptionInput"
                    class="textarea" style="width: 100%; background-color: rgba(0, 0, 0, 0);" autofocus>${description}
                </textarea>

                <div class="column is-narrow columns is-flex is-flex-direction-column m-0 mx-2 p-0">
                    <button onclick="confirmBtn_onClick()" class="column button">Potwierdź</button>
                    <button onclick="rejectBtn_onClick()" class="column button">Odrzuć</button>
                </div>
            </div>`;
        }

        async function rejectBtn_onClick() {
            initText();
        }

        async function confirmBtn_onClick() {
            const newDescription = document.getElementById("descriptionInput").value.trim();

            const formData = new FormData();
            formData.append('description', newDescription);

            try {
                var csrfToken = document.querySelector('meta[name="csrf-token"]').content;
                const response = await fetch('/user/changeDescription', {
                    method: 'POST',
                    headers: {
                        "X-CSRF-Token": csrfToken
                    },
                    body: formData
                });

                if (response.ok) {
                    description = newDescription;
                    initText();
                } else {
                    console.error('Wystąpił błąd podczas aktualizacji opisu użytkownika.');
                }
            } catch (error) {
                console.error('Wystąpił błąd podczas wysyłania danych:', error);
            }
        }

        initText();
    </script>
</div>

app/views/user/profile.html.erb
<div class="columns is-flex is-flex-direction-column p-3 m-0" style="height: 100%; width: 960px; overflow-y: auto;">
  <% if @profile.present? %>
    <% @is_logged = session[:user].present? %>
    <% if @is_logged %>
        <% @is_my_account = @profile.login == session[:user]['login'] && @profile.login == params[:login] %>
    <% else %>
        <% @is_my_account = false %>
    <% end %>
    <div class="columns is-flex is-flex-direction-column column is-narrow" style="height: 100%; width: 960px;">
      <div class="columns p-0 m-0 is-flex is-align-items-center" style="height: 200px;">
        <div class="column p-0 m-0 is-narrow" style="height: 100%; width: 200px;">
          <%= render partial: "user/profile_avatar", locals: { avatar_url: @profile.avatar_url, is_my_account: @is_my_account } %>
        </div>

        <div class="column p-0 m-0 is-flex is-justify-content-flex-start is-flex-direction-column is-align-items-center columns" style="height: 100%;">
          <span class="column is-narrow p-0">
            <span class="is-size-3"><%= @profile.login %></span>
          </span>

        <div class="column is-narrow py-0 px-6 is-flex is-justify-content-space-between is-size-4" style="width: 100%;">
          <span class="icon-text">
            <i class="icon fa-regular has-text-info-40 is-flex is-align-items-center">
              <i class="fas fa-comments"></i>
            </i>
            <span class="ml-3"><%= @profile.posts_count %></span>
          </span>

          <span class="icon-text">
            <i class="icon fa-regular has-text-info-40 is-flex is-align-items-center">
              <i class="fas fa-comment"></i>
            </i>
            <span class="ml-3"><%= @profile.comments_count %></span>
          </span>

          <span class="icon-text">
            <i class="icon fa-regular has-text-info-40 is-flex is-align-items-center">
              <i class="fas fa-thumbs-up"></i>
            </i>
            <span class="ml-3"><%= @profile.likes_count %></span>
          </span>
        </div>
        <%= render partial: "user/profile_description", locals: { description: @profile.description, is_my_account: @is_my_account } %>
      </div>
    </div>

    <div class="column columns" style="width: 100%; height: 100%">
      <div class="column is-narrow" style="width: 200px;">
        <% if @is_logged && !@is_my_account %>
          <%= form_with(url: toggle_friend_path, method: :post) do |form| %>
            <%= form.hidden_field :login, value: params[:login] %>
            <%= form.button class: "button", type: "submit" do %>
              <%= @profile.is_my_friend ? "Usuń ze znajomych" : "Dodaj do znajomych" %>
            <% end %> 
          <% end %>
        <% end %>
      </div>

      <div class="column">
        <% if @is_my_account %>
          <% if @profile.friends.present? %>
            <p class="is-size-3">Lista znajomych</p>
              <div class="columns is-flex-direction-column">
                <% @profile.friends.each do |friend| %>
                  <div class="column p-0 m-0 is-size-4 columns">
                    <%= link_to user_profile_path(friend.login), class: "column" do %>
                        <%= friend.login %>
                    <% end %>
                    <%= form_with(url: toggle_friend_path, method: :post, class: "column is-flex is-align-items-center", style: "width: 100%") do |form| %>
                      <%= form.hidden_field :login, value: friend.login %>
                      <%= form.button class: "button", type: "submit" do %>
                        Usuń ze znajomych
                      <% end %> 
                    <% end %>
                  </div>
                <% end %>
              </div>
          <% else %>
            <p class="is-size-3">Brak znajomych na liście.</p>
          <% end %>
        <% end %>
      </div>
    <div>

  <% else %>
    <div class="is-flex is-align-items-center is-justify-content-center" style="height: 100%; width: 100%;">
      <span class="is-size-1">
        Użytkownik <%= params[:login] %> nie istnieje!
      </span>
    </div>
  <% end %>
</div>