config/routes.rb
Rails.application.routes.draw do
  resources :forums

  get 'forum(/:page(/:tags))', to: 'forum#index', as: 'forum_index'
  post 'forum/search_by_tags', to: 'forum#search_by_tags', as: 'search_by_tags'
  post 'forum/search_by_page', to: 'forum#search_by_page', as: 'search_by_page'
  post 'forum/create_post', to: 'forum#create_post', as: 'create_post'
  post 'forum/toggle_post_like', to: 'forum#toggle_post_like', as: 'toggle_post_like'
  post 'forum/create_comment', to: 'forum#create_comment', as: 'create_comment'
  post 'forum/toggle_comment_like', to: 'forum#toggle_comment_like', as: 'toggle_comment_like'

  get 'login', to: 'login#index', as: 'login_index'
  post 'login', to: 'login#login'

  get 'register', to: 'register#index', as: 'register_index'
  post 'register', to: 'register#register'

  get 'user/:login', to: 'user#profile', as: 'user_profile'
  post 'user/logout', to: 'user#logout', as: 'user_logout'
  post 'user/changeAvatar', to: 'user#change_avatar'
  post 'user/changeDescription', to: 'user#change_description'
  post 'user/toggleFriend', to: 'user#toggle_friend', as: 'toggle_friend'

  get "up" => "rails/health#show", as: :rails_health_check

   root "forum#index"
end

Rails.application.routes.default_url_options[:host] = 'localhost:3000'

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    def index
        redirect_to forum_index_path if session[:user].present?
    end
  
    def show
    end
  
    def register
        login = params[:login]
        email = params[:email]
        password = params[:password]
        repeat_password = params[:repeat_password]

        if password.nil? || password.length < 3
            @error = "Hasło musi mieć co najmniej 3 znaki."
            render :index
            return
        end
    
        if User.exists?(login: login)
            @error = "Podany login już istnieje."
            render :index
            return
        end
    
        if email.blank?
              @error = "Nie podano adresu email."
            render :index
            return
        end
    
        if User.exists?(email: email)
            @error = "Podany email jest już zarejestrowany."
            render :index
            return
        end
    
        if password != repeat_password
            @error = "Błędnie powtórzono hasło."
            render :index
            return
        end
    
        user = User.new(login: login, email: email, password: password)
        user.created_at = Time.now
    
        if user.save
              session[:user] = { login: login }
              redirect_to forum_index_path
        else
              @error = "Nie udało się zarejestrować użytkownika."
              render :index
        end
      end
  end
  

app/views/register/_form.html.erb
<%= form_with(url: register_path, method: "post", class: "has-background-black-ter box is-flex is-flex-direction-column is-align-items-center my-3 is-rounded is-standard-width") do |form| %>
    <div class="field is-80percent-width mb-4">
        <p class="control has-icons-left">
              <%= form.text_field :login, class: "input is-medium", placeholder: "Wprowadź login", required: true %>
              <span class="icon is-small is-left">
                  <i class="fas fa-user"></i>
              </span>
        </p>
    </div>

    <div class="field is-80percent-width mb-4">
        <p class="control has-icons-left">
              <%= form.email_field :email, class: "input is-medium", placeholder: "Wprowadź email", required: true %>
              <span class="icon is-small is-left">
                  <i class="fas fa-envelope"></i>
              </span>
        </p>
    </div>

    <div class="field is-80percent-width mb-4">
        <p class="control has-icons-left">
              <%= form.password_field :password, class: "input is-medium", placeholder: "Wprowadź hasło", required: true %>
              <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
              </span>
        </p>
    </div>

    <div class="field is-80percent-width mb-4">
        <p class="control has-icons-left">
              <%= form.password_field :repeat_password, class: "input is-medium", placeholder: "Powtórz hasło", required: true %>
              <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
              </span>
        </p>
    </div>

    <% if error %>
        <p class="has-text-centered mb-4 has-text-danger"><%= error %></p>
    <% end %>

    <div class="field">
        <div class="control">
              <%= form.submit "Zarejestruj się", class: "button is-primary is-medium" %>
        </div>
    </div>
<% end %>

app/views/register/index.html.erb
<div class="is-flex is-flex-direction-column is-align-items-center p-0 m-0">
    <%= link_to "Wróć do strony głównej", "/forum", class: "has-text-grey-lighter" %>
    
    <%= render "form", error: @error.present? ? @error : nil %>
    
    <div>
        <%= link_to "Zaloguj się", "login", class: "has-text-warning" %>
        <span>, jeżeli posiadasz już konto!</span>
    </div>
</div>