config/routes.rb
Rails.application.routes.draw do
  resources :forums

  get 'forum(/:page(/:tags))', to: 'forum#index', as: 'forum_index'
  post 'forum/search_by_tags', to: 'forum#search_by_tags', as: 'search_by_tags'
  post 'forum/search_by_page', to: 'forum#search_by_page', as: 'search_by_page'
  post 'forum/create_post', to: 'forum#create_post', as: 'create_post'
  post 'forum/toggle_post_like', to: 'forum#toggle_post_like', as: 'toggle_post_like'
  post 'forum/create_comment', to: 'forum#create_comment', as: 'create_comment'
  post 'forum/toggle_comment_like', to: 'forum#toggle_comment_like', as: 'toggle_comment_like'

  get 'login', to: 'login#index', as: 'login_index'
  post 'login', to: 'login#login'

  get 'register', to: 'register#index', as: 'register_index'
  post 'register', to: 'register#register'

  get 'user/:login', to: 'user#profile', as: 'user_profile'
  post 'user/logout', to: 'user#logout', as: 'user_logout'
  post 'user/changeAvatar', to: 'user#change_avatar'
  post 'user/changeDescription', to: 'user#change_description'
  post 'user/toggleFriend', to: 'user#toggle_friend', as: 'toggle_friend'

  get "up" => "rails/health#show", as: :rails_health_check

   root "forum#index"
end

Rails.application.routes.default_url_options[:host] = 'localhost:3000'

app/views/layouts/_navlist.html.erb
<aside class="menu border-right p-3 is-size-6">
  <p class="menu-label has-text-white mb-2 has-text-weight-bold">
    Wybierz
  </p>

  <ul class="menu-list">
    <li class="mb-1">
      <%= link_to forum_index_path, class: "button is-ghost has-text-white px-3 py-0" do %>
        <span class="icon mr-1">
          <i class="fas fa-comments"></i>
        </span>
        <span>Forum</span>
      <% end %>
    </li>

    <% if session[:user].present? %>
      <% login = session[:user]['login'] %>
      <li class="mb-1">
        <%= link_to user_profile_path(login), class: "button is-ghost has-text-white px-3 py-0" do %>
        <span class="icon mr-1">
            <i class="fas fa-sign-in-alt"></i>
        </span>
        <span><%= login %></span>
        <% end %>
      </li>
      <li class="mb-1">
        <%= form_tag(user_logout_path, method: :post) do %>
          <button type="submit" class="button is-ghost has-text-white px-3 py-0">
            <span class="icon mr-1">
              <i class="fas fa-power-off"></i>
            </span>
            <span>Wyloguj</span>
          </button>
        <% end %>
      </li>
    <% else %>
      <li class="mb-1">
        <%= link_to "login", class: "button is-ghost has-text-white px-3 py-0" do %>
          <span class="icon mr-1">
            <i class="fas fa-sign-in-alt"></i>
          </span>
          <span>Logowanie</span>
        <% end %>
      </li>

      <li class="mb-1">
        <%= link_to "register", class: "button is-ghost has-text-white px-3 py-0" do %>
          <span class="icon mr-1">
            <i class="fas fa-user-plus"></i>
          </span>
          <span>Rejestracja</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-grey-darker">
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bulma@latest/css/bulma.min.css" %>
    <%= stylesheet_link_tag"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
			html,
			body {
				height: 100%;
				width: 100%;
				margin: 0;
				padding: 0;
				overflow: hidden;
			}
    </style>
  </head>

  <body class="columns p-0 m-0 is-family-primary" style="height: 100%;">
    <div class="column p-0 m-0 is-narrow has-background-black-ter">
      <%= render 'layouts/navlist' %>
    </div>

    <div class="column p-0 m-0 is-flex is-justify-content-center is-align-items-center" style="width: 100%; height: 100%; overflow-y: auto">
      <%= yield %>
    </div>
  </body>
</html>